# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  # workflow_dispatch:
  #   inputs:
  #     input_environment:
  #       description: 'Input environment'
  #       required: true 
  #       type: choice
  #       options:
  #       - DEV
  #       - PROD  
# on:
#   workflow_dispatch:
#     branches:
#     - main

jobs:
  build:
    name: Building and Pushing the Image
    runs-on: ubuntu-latest
    environment: DEV  ## ${{ inputs.input_environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/argocd:${{github.run_number}}


    # - name: Build, tag, and push image to Amazon ECR
    #   id: build-image
    #   env:
    #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #     ECR_REPOSITORY: gitops-argocd

    #   run: |
    #     # Build a docker container and push it to ECR
    #     git_hash=$(git rev-parse --short "$GITHUB_SHA")
    #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash .
    #     echo "Pushing image to ECR..."
    #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash
    #     echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash"
        
    # - name: Update Version
    #   run: |
    #       git_hash=$(git rev-parse --short "$GITHUB_SHA")
    #       version=$(cat ./charts/helm-example/values.yaml | grep version: | awk '{print $2}')
    #       sed -i "s/$version/${GITHUB_REF##*/}-$git_hash/" ./charts/helm-example/values.yaml
          
    # - name: Commit and push changes
    #   uses: devops-infra/action-commit-push@v0.3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     commit_message: Version updated